import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.scss";
import { cookies } from "next/headers";
import type { ResolvedWebTheme, WebTheme } from "@/app/_types";
import { WebThemeProvider } from "@/app/_providers/WebThemeProvider";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function normalizeTheme(value: string | undefined): WebTheme {
    if(value === "light" || value === "dark" || value === "auto") {
        return value;
    }

    return "auto";
}

function getServerResolvedTheme(theme: WebTheme): ResolvedWebTheme {
    if(theme === "dark") {
        return "dark";
    }

    return "light";
}

function createThemeInitScript(initialTheme: WebTheme) {
    return `
(function() {
    try {
        var theme = ${JSON.stringify(initialTheme)};

        if(theme !== "light" && theme !== "dark" && theme !== "auto") {
            theme = "auto";
        }

        var resolvedTheme = theme;

        if(theme === "auto") {
            resolvedTheme = window.matchMedia("(prefers-color-scheme: dark)").matches
                ? "dark"
                : "light";
        }

        document.documentElement.dataset.theme = resolvedTheme;
    } catch(error) {
        document.documentElement.dataset.theme = "light";
    }
})();
`;
}

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {
    const cookieStore = await cookies();

    const initialTheme = normalizeTheme(cookieStore.get("webTheme")?.value);
    const initialResolvedTheme = getServerResolvedTheme(initialTheme);

    return (
        <html
            lang="en"
            data-theme={initialResolvedTheme}
            suppressHydrationWarning
        >
        <head>
            <script
                dangerouslySetInnerHTML={{
                    __html: createThemeInitScript(initialTheme),
                }}
            />
        </head>

        <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <WebThemeProvider
            initialTheme={initialTheme}
            initialResolvedTheme={initialResolvedTheme}
        >
            {children}
        </WebThemeProvider>
        </body>
        </html>
    );
}